import Foundation

// Add PhraseCategory enum
enum PhraseCategory {
    case normal, warning, game, never, timedChallenge
}

// Add PhraseData struct
struct PhraseData {
    let text: String
    let category: PhraseCategory
    let duration: Double?

    // Convenience initializer for phrases without duration
    init(text: String, category: PhraseCategory) {
        self.text = text
        self.category = category
        self.duration = nil
    }

    // Initializer for timed challenges
    init(text: String, category: PhraseCategory, duration: Double) {
        self.text = text
        self.category = category
        self.duration = duration
    }
}

class GameModel {
    private(set) var players: [String] = []
    private let maxPlayers = 15
    
    // Update phrases array to use PhraseData
    private var phrases: [PhraseData] = [
        // Normal category phrases
        PhraseData(text: "[Name], se já comeste um pastel de nata frio, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já dançou o vira numa festa popular distribui 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já perdeste as chaves numa noite de copos, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já foram ao Bairro Alto esta semana apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], distribui 2 penalidades a cada jogador que já tenhas visto bêbado.", category: .normal),
        PhraseData(text: "Quem já pediu uma bifana às 3 da manhã distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já mentiste sobre o teu sotaque, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que têm mais de 5 contactos bloqueados no telemóvel apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste apanhado(a) a cantar fado no duche, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já ficou sem bateria no telemóvel numa festa apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já beijaste alguém numa praia do Algarve, distribui 3 penalidades.", category: .normal),
        PhraseData(text: "Os que já gritaram 'Força Portugal!' num jogo apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já enviaste uma mensagem picante por engano, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já fez sexo no carro distribui 4 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fingiste um orgasmo, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já tiveram um ménage à trois apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já usaste um brinquedo sexual, distribui 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi apanhado(a) pelos pais em algo spicy apanha 4 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já tiveste um sonho erótico com alguém desta sala, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Os que já fizeram sexting durante uma aula ou reunião distribuem 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao São João no Porto, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já comeu uma francesinha distribui 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já perdeste o telemóvel numa noite de copos, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já foram ao Rock in Rio Lisboa apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], distribui 2 penalidades a cada jogador que já tenhas visto a dançar.", category: .normal),
        PhraseData(text: "Quem já pediu um copo de vinho do Porto às 3 da manhã distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já mentiste sobre a tua idade, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que têm mais de 10 apps no telemóvel apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste apanhado(a) a cantar música pimba, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já ficou sem dinheiro numa festa apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já beijaste alguém numa festa de aldeia, distribui 3 penalidades.", category: .normal),
        PhraseData(text: "Os que já gritaram 'golo!' num café apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já enviaste uma mensagem para o ex por engano, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já fez sexo na praia distribui 4 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fingiste gostar de alguém, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já tiveram um encontro às cegas apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já usaste uma app de encontros, distribui 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi apanhado(a) a ver pornografia apanha 4 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já tiveste um sonho erótico com um amigo, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Os que já fizeram sexting no trabalho distribuem 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já mandaste uma foto spicy, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já ficou com alguém só por causa de uma aposta apanha 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], diz o nome da última pessoa com quem dormiste ou apanha 4 penalidades.", category: .normal),
        PhraseData(text: "Os que já experimentaram roleplay na cama distribuem 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fizeste sexo numa casa de banho pública, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já teve um crush num professor ou chefe apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já usaste algemas, distribui 4 penalidades.", category: .normal),
        PhraseData(text: "Os que já fizeram striptease para alguém apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já tiveste sexo ao ar livre, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi a um motel distribui 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já caíste numa noite de copos, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já dançou em cima de uma mesa distribui 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já vomitaste numa festa, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já foram expulsos de um bar apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já dormiste na rua depois de beber, apanha 3 penalidades.", category: .normal),
        PhraseData(text: "Quem já perdeu uma aposta bêbado distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste apanhado(a) a roubar copos de um bar, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já beberam um shot de absinto apanham 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já cantaste karaoke bêbado(a), distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já acordou sem saber onde estava apanha 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao Minho numa romaria, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já comeram tripas à moda do Porto distribuem 3 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já apanhaste um susto num castelo, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi a uma tourada distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já nadaste no Douro, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já gritaram numa manif apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já comeste um chouriço assado, distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi ao Pingo Doce de pijama apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste a um concerto no Coliseu, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já beberam vinho verde num piquenique distribuem 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fizeste campismo na Serra da Estrela, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já andou de tuk-tuk em Lisboa distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já subiste à Torre dos Clérigos, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já comeram um bolo-rei fora do Natal apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste a um mercado medieval, distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já bebeu uma ginjinha em Óbidos apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao Oceanário de Lisboa, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já apanharam boleia numa estrada nacional distribuem 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já comeste sardinha assada no verão, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi ao Carnaval de Torres Vedras distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fizeste uma selfie na Ponte 25 de Abril, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já beberam um café na Brasileira apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao santuário de Fátima, distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já comeu um leitão da Bairrada apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste a uma feira popular, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já dançaram numa queima das fitas distribuem 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já subiste ao Castelo de São Jorge, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já foi ao Festival do Crato apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já comeste uma alheira frita, distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já viram o fogo-de-artifício no S. João apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao Palácio da Pena, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já bebeu um moscatel de Setúbal distribui 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já fizeste surf na Nazaré, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já comeram caldo verde numa festa apanham 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao Mercado da Ribeira, distribui 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já andou de elétrico em Lisboa apanha 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já comeste um travesseiro de Sintra, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Os que já foram ao Douro Vinhateiro distribuem 2 penalidades.", category: .normal),
        PhraseData(text: "[Name], se já foste ao Castelo de Almourol, apanha 2 penalidades.", category: .normal),
        PhraseData(text: "Quem já bebeu uma caipirinha na Costa da Caparica apanha 2 penalidades.", category: .normal),
        // Game category phrases
        PhraseData(text: "Sardinha ou caracol? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a gritar 'saúde!' apanha 2 penalidades.", category: .game),
        PhraseData(text: "Benfica ou Sporting? Votem todos ao mesmo tempo, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem consegue nomear 5 jogadores do Porto em 10 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita o Cristiano Ronaldo em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O último a tocar no nariz apanha 2 penalidades.", category: .game),
        PhraseData(text: "Cerveja ou gin? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz uma careta. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de dormir com um ex? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz uma frase de engate em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Pastel de nata ou bolo de arroz? Votem, a minoria apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a levantar a mão distribui 3 penalidades.", category: .game),
        PhraseData(text: "Porto ou Lisboa? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 3 cantores de fado em 15 segundos distribui 2 penalidades.", category: .game),
        PhraseData(text: "[Name], imita um galo a cantar. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O último a dizer 'caralho' apanha 2 penalidades.", category: .game),
        PhraseData(text: "Vinho tinto ou vinho branco? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz um piscar de olho sexy. O primeiro a corar apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de chegar atrasado? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz algo em francês em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Bacalhau ou chouriço? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a bater palmas apanha 2 penalidades.", category: .game),
        PhraseData(text: "Fado ou pimba? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 5 praias portuguesas em 15 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita o Tony Carreira. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a tocar na orelha distribui 2 penalidades.", category: .game),
        PhraseData(text: "Sangria ou caipirinha? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz uma pose de modelo. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de casar primeiro? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz um palavrão em 5 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Francesinha ou bifana? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a dizer 'olá' apanha 2 penalidades.", category: .game),
        PhraseData(text: "Verão ou inverno? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 4 cidades portuguesas em 10 segundos distribui 2 penalidades.", category: .game),
        PhraseData(text: "[Name], imita um político português. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a tocar na cabeça distribui 2 penalidades.", category: .game),
        PhraseData(text: "Coca-cola ou sumol? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz um som de animal. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de esquecer o jogo? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz algo em inglês em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Sopas ou grelhados? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a levantar-se apanha 2 penalidades.", category: .game),
        PhraseData(text: "Rock ou pop? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 5 marcas portuguesas em 15 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita um bebé a chorar. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a dizer 'sim' distribui 2 penalidades.", category: .game),
        PhraseData(text: "Café ou chá? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz uma dança ridícula. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de ser famoso? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz uma piada em 15 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Mar ou montanha? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a piscar os olhos apanha 2 penalidades.", category: .game),
        PhraseData(text: "Cão ou gato? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 3 rios portugueses em 10 segundos distribui 2 penalidades.", category: .game),
        PhraseData(text: "[Name], imita o sotaque algarvio. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a tocar no pé distribui 2 penalidades.", category: .game),
        PhraseData(text: "Pizza ou hambúrguer? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz um barulho de mota. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de ganhar o Euromilhões? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz algo em espanhol em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Sol ou chuva? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a dizer 'adeus' apanha 2 penalidades.", category: .game),
        PhraseData(text: "Doce ou salgado? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 5 filmes portugueses em 15 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita um porco. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a tocar na mesa distribui 2 penalidades.", category: .game),
        PhraseData(text: "Vodka ou tequila? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz uma cara assustada. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de ser um mau cozinheiro? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz um provérbio português em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Peixe ou carne? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a levantar o copo apanha 2 penalidades.", category: .game),
        PhraseData(text: "Azul ou vermelho? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 4 festas populares em 15 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita o sotaque alentejano. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a dizer 'não' distribui 2 penalidades.", category: .game),
        PhraseData(text: "Frango ou porco? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz um som de gaivota. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de chorar num filme? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz algo em italiano em 10 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Dia ou noite? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a tocar na cadeira apanha 2 penalidades.", category: .game),
        PhraseData(text: "Grande ou pequeno? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 5 monumentos portugueses em 15 segundos distribui 3 penalidades.", category: .game),
        PhraseData(text: "[Name], imita um cão a ladrar. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a levantar o pé distribui 2 penalidades.", category: .game),
        PhraseData(text: "Água ou refrigerante? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz uma cara de zangado. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de perder as chaves? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz uma palavra com 5 letras em 5 segundos ou apanha 2 penalidades.", category: .game),
        PhraseData(text: "Campo ou cidade? Votem já, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "O último a dizer 'boa' apanha 2 penalidades.", category: .game),
        PhraseData(text: "Riso ou choro? Votem todos, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "Quem nomeia 4 sobremesas portuguesas em 10 segundos distribui 2 penalidades.", category: .game),
        PhraseData(text: "[Name], imita o sotaque minhoto. Se ninguém rir, apanha 2 penalidades.", category: .game),
        PhraseData(text: "O primeiro a tocar no copo distribui 2 penalidades.", category: .game),
        PhraseData(text: "Gelado ou bolo? Votem, a minoria apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], faz um som de vento. O primeiro a rir apanha 2 penalidades.", category: .game),
        PhraseData(text: "Quem é o mais provável de dormir na praia? Votem, o mais votado apanha 3 penalidades.", category: .game),
        PhraseData(text: "[Name], diz algo em alemão em 10 segundos ou apanha 2 penalidades.", category: .game),
        // Warning category phrases
        PhraseData(text: "A partir de agora, é proibido dizer 'claro'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque alentejano até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido tocar no telemóvel até ao fim do jogo. Quem tocar, apanha 3 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em rimas até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, todos têm de chamar [Name] de 'meu rei/minha rainha'. Quem esquecer, apanha 1 penalidade.", category: .warning),
        PhraseData(text: "[Name], tens de terminar cada frase com 'saudinha'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido rir até ao próximo turno de [Name]. Quem rir, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em sussurros até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'copo'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como locutor de rádio até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido dizer 'sim' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque algarvio até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido apontar para alguém. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em perguntas até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido mexer no cabelo até ao próximo turno de [Name]. Quem mexer, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de começar cada frase com 'caramba'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'não'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em gritos até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido usar a palavra 'beber' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses uma criança até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido cruzar os braços. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque minhoto até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido levantar-se até ao próximo turno de [Name]. Quem se levantar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em afirmações até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, todos têm de chamar [Name] de 'chefe'. Quem esquecer, apanha 1 penalidade.", category: .warning),
        PhraseData(text: "[Name], tens de terminar cada frase com 'meu Deus'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido olhar para o telemóvel até ao fim do jogo. Quem olhar, apanha 3 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em cantigas até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'amigo'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um velho até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido dizer 'ok' até ao próximo turno de [Name]. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque lisboeta até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido tocar na mesa. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em inglês até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido coçar-se até ao fim do jogo. Quem coçar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de começar cada frase com 'olhem'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'bom'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz alta até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido usar a palavra 'jogo' até ao próximo turno de [Name]. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um poeta até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido piscar os olhos por 10 segundos. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque madeirense até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido mexer os pés até ao fim do jogo. Quem mexer, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em frases curtas até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, todos têm de chamar [Name] de 'princesa/príncipe'. Quem esquecer, apanha 1 penalidade.", category: .warning),
        PhraseData(text: "[Name], tens de terminar cada frase com 'carago'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido rir de [Name] até ao próximo turno dele(a). Quem rir, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em murmúrios até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'saúde'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um rei/rainha até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido dizer 'talvez' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque transmontano até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido apontar para o chão. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em espanhol até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido cruzar as pernas até ao próximo turno de [Name]. Quem cruzar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de começar cada frase com 'epa'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'fixe'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz grave até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido usar a palavra 'penalidade' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um apresentador de TV até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido tocar no nariz. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque açoriano até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido mexer as mãos até ao próximo turno de [Name]. Quem mexer, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em francês até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, todos têm de chamar [Name] de 'doutor/doutora'. Quem esquecer, apanha 1 penalidade.", category: .warning),
        PhraseData(text: "[Name], tens de terminar cada frase com 'pronto'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido olhar para [Name] até ao fim do jogo. Quem olhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz aguda até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'olá'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um turista até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido dizer 'gosto' até ao próximo turno de [Name]. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque portuense até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido tocar na cadeira. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em italiano até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido mexer a cabeça até ao fim do jogo. Quem mexer, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de começar cada frase com 'olha'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'bem'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz lenta até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido usar a palavra 'festa' até ao próximo turno de [Name]. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um cantor até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido tocar no copo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque ribatejano até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido levantar o copo até ao fim do jogo. Quem levantar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em alemão até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "A partir de agora, todos têm de chamar [Name] de 'amigo/amiga'. Quem esquecer, apanha 1 penalidade.", category: .warning),
        PhraseData(text: "[Name], tens de terminar cada frase com 'tá bem'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido olhar para o chão até ao próximo turno de [Name]. Quem olhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz rápida até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'adeus'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um pirata até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido dizer 'mal' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar com sotaque beirão até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, é proibido tocar na cara. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], só podes falar em frases longas até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        PhraseData(text: "Proibido mexer os ombros até ao próximo turno de [Name]. Quem mexer, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de começar cada frase com 'pá'. Cada esquecimento, 1 penalidade.", category: .warning),
        PhraseData(text: "A partir de agora, ninguém pode dizer 'pena'. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], fala só em voz de desenho animado até ao teu próximo turno. Cada erro, 1 penalidade.", category: .warning),
        PhraseData(text: "Proibido usar a palavra 'noite' até ao fim do jogo. Quem falhar, apanha 2 penalidades.", category: .warning),
        PhraseData(text: "[Name], tens de falar como se fosses um cientista até à tua próxima vez. Cada erro, 2 penalidades.", category: .warning),
        // Never category phrases
        PhraseData(text: "Eu nunca comi um cozido à portuguesa com chuva lá fora.", category: .never),
        PhraseData(text: "Eu nunca dancei pimba numa festa de aldeia.", category: .never),
        PhraseData(text: "Eu nunca disse 'só mais uma imperial' e falhei.", category: .never),
        PhraseData(text: "Eu nunca perdi um elétrico por 1 segundo.", category: .never),
        PhraseData(text: "Eu nunca chorei a ouvir fado ao vivo.", category: .never),
        PhraseData(text: "Eu nunca roubei um guardanapo de um café.", category: .never),
        PhraseData(text: "Eu nunca fingi gostar de bacalhau.", category: .never),
        PhraseData(text: "Eu nunca fui a um arraial sem dançar.", category: .never),
        PhraseData(text: "Eu nunca gritei num jogo de futebol em casa.", category: .never),
        PhraseData(text: "Eu nunca dormi na praia depois de uma festa.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo num festival.", category: .never),
        PhraseData(text: "Eu nunca beijei alguém numa discoteca sem saber o nome.", category: .never),
        PhraseData(text: "Eu nunca tive um one night stand num hostel.", category: .never),
        PhraseData(text: "Eu nunca usei Tinder enquanto estava numa relação.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo na casa de um amigo.", category: .never),
        PhraseData(text: "Eu nunca tive um sonho molhado com um colega de trabalho.", category: .never),
        PhraseData(text: "Eu nunca experimentei sexo anal.", category: .never),
        PhraseData(text: "Eu nunca fui a um clube de strip.", category: .never),
        PhraseData(text: "Eu nunca fiz um vídeo picante.", category: .never),
        PhraseData(text: "Eu nunca traí alguém.", category: .never),
        PhraseData(text: "Eu nunca comi sardinha assada sem beber vinho.", category: .never),
        PhraseData(text: "Eu nunca perdi uma aposta num bar.", category: .never),
        PhraseData(text: "Eu nunca dancei numa mesa bêbado(a).", category: .never),
        PhraseData(text: "Eu nunca vomitei num táxi.", category: .never),
        PhraseData(text: "Eu nunca bebi um shot de aguardente.", category: .never),
        PhraseData(text: "Eu nunca dormi num banco de jardim.", category: .never),
        PhraseData(text: "Eu nunca roubei uma bebida de alguém.", category: .never),
        PhraseData(text: "Eu nunca fingi estar sóbrio(a) na frente da polícia.", category: .never),
        PhraseData(text: "Eu nunca acordei com um estranho ao meu lado.", category: .never),
        PhraseData(text: "Eu nunca caí de uma cadeira por estar bêbado(a).", category: .never),
        PhraseData(text: "Eu nunca fui ao Porto sem comer uma francesinha.", category: .never),
        PhraseData(text: "Eu nunca nadei no mar à noite.", category: .never),
        PhraseData(text: "Eu nunca gritei numa manifestação.", category: .never),
        PhraseData(text: "Eu nunca comi um chouriço assado em casa.", category: .never),
        PhraseData(text: "Eu nunca fui expulso(a) de uma festa.", category: .never),
        PhraseData(text: "Eu nunca bebi vinho do Porto ao pequeno-almoço.", category: .never),
        PhraseData(text: "Eu nunca dancei o vira com um desconhecido.", category: .never),
        PhraseData(text: "Eu nunca perdi o telemóvel numa praia.", category: .never),
        PhraseData(text: "Eu nunca chorei por causa de um jogo de futebol.", category: .never),
        PhraseData(text: "Eu nunca roubei um souvenir de um bar.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo ao som de fado.", category: .never),
        PhraseData(text: "Eu nunca beijei alguém numa igreja.", category: .never),
        PhraseData(text: "Eu nunca tive um encontro num castelo.", category: .never),
        PhraseData(text: "Eu nunca mandei uma mensagem nua por engano.", category: .never),
        PhraseData(text: "Eu nunca fingi estar doente para não sair com alguém.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo num parque.", category: .never),
        PhraseData(text: "Eu nunca tive um crush num estranho no metro.", category: .never),
        PhraseData(text: "Eu nunca usei uma pickup line num bar.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo numa tenda.", category: .never),
        PhraseData(text: "Eu nunca beijei alguém só por uma aposta.", category: .never),
        PhraseData(text: "Eu nunca comi um pastel de nata quente da padaria.", category: .never),
        PhraseData(text: "Eu nunca dancei numa rua cheia de gente.", category: .never),
        PhraseData(text: "Eu nunca disse 'amo-te' bêbado(a).", category: .never),
        PhraseData(text: "Eu nunca perdi um sapato numa festa.", category: .never),
        PhraseData(text: "Eu nunca bebi uma ginjinha com eles.", category: .never),
        PhraseData(text: "Eu nunca dormi num elétrico.", category: .never),
        PhraseData(text: "Eu nunca roubei flores de um jardim público.", category: .never),
        PhraseData(text: "Eu nunca fingi ser estrangeiro(a) para impressionar.", category: .never),
        PhraseData(text: "Eu nunca cantei o hino nacional bêbado(a).", category: .never),
        PhraseData(text: "Eu nunca caí numa escadaria pública.", category: .never),
        PhraseData(text: "Eu nunca fui a uma festa de São João sem martelo.", category: .never),
        PhraseData(text: "Eu nunca comi tripas sem vinho.", category: .never),
        PhraseData(text: "Eu nunca gritei numa ponte.", category: .never),
        PhraseData(text: "Eu nunca bebi uma cerveja quente.", category: .never),
        PhraseData(text: "Eu nunca dancei com um chapéu na cabeça.", category: .never),
        PhraseData(text: "Eu nunca perdi um autocarro por estar a comer.", category: .never),
        PhraseData(text: "Eu nunca roubei um copo de um festival.", category: .never),
        PhraseData(text: "Eu nunca fingi gostar de touradas.", category: .never),
        PhraseData(text: "Eu nunca chorei numa esplanada.", category: .never),
        PhraseData(text: "Eu nunca dormi num carro depois de beber.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo numa varanda.", category: .never),
        PhraseData(text: "Eu nunca beijei alguém num elevador.", category: .never),
        PhraseData(text: "Eu nunca tive um one night stand num bar.", category: .never),
        PhraseData(text: "Eu nunca usei uma app para sexo casual.", category: .never),
        PhraseData(text: "Eu nunca fiz sexo numa piscina.", category: .never),
        PhraseData(text: "Eu nunca tive um sonho erótico com um chefe.", category: .never),
        PhraseData(text: "Eu nunca experimentei bondage.", category: .never),
        PhraseData(text: "Eu nunca fui a uma sauna sexy.", category: .never),
        PhraseData(text: "Eu nunca gravei um áudio spicy.", category: .never),
        PhraseData(text: "Eu nunca menti sobre um parceiro sexual.", category: .never),
        PhraseData(text: "Eu nunca comi uma bifana sem mostarda.", category: .never),
        PhraseData(text: "Eu nunca dancei num barco.", category: .never),
        PhraseData(text: "Eu nunca disse 'só mais um copo' e fiquei até de manhã.", category: .never),
        PhraseData(text: "Eu nunca perdi um voo por estar de ressaca.", category: .never),
        PhraseData(text: "Eu nunca bebi um licor Beirão num bar.", category: .never),
        PhraseData(text: "Eu nunca dormi numa esplanada.", category: .never),
        PhraseData(text: "Eu nunca roubei um chapéu de alguém.", category: .never),
        PhraseData(text: "Eu nunca fingi ser rico(a) para impressionar.", category: .never),
        PhraseData(text: "Eu nunca cantei pimba num karaoke.", category: .never),
        PhraseData(text: "Eu nunca caí de uma bicicleta bêbado(a).", category: .never),
        PhraseData(text: "Eu nunca fui ao Algarve sem ir à praia.", category: .never),
        PhraseData(text: "Eu nunca comi um bolo-rei em julho.", category: .never),
        PhraseData(text: "Eu nunca gritei num miradouro.", category: .never),
        PhraseData(text: "Eu nunca bebi uma sangria sozinho(a).", category: .never),
        PhraseData(text: "Eu nunca dancei com um desconhecido na rua.", category: .never),
        PhraseData(text: "Eu nunca perdi uma carteira numa festa.", category: .never),
        PhraseData(text: "Eu nunca roubei um cartaz de um bar.", category: .never),
        PhraseData(text: "Eu nunca fingi gostar de vinho caro.", category: .never),
        PhraseData(text: "Eu nunca chorei por perder uma aposta.", category: .never),
        PhraseData(text: "Eu nunca dormi ao relento depois de uma festa.", category: .never),
        // Timed Challenge category phrases
        PhraseData(text: "[Name], faz 5 agachamentos em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 3 pratos típicos portugueses em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], bebe meio copo em 8 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 8.0),
        PhraseData(text: "[Name], imita o Quadro em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], diz 5 marcas de cerveja em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança sexy em 30 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 30.0),
        PhraseData(text: "[Name], conta uma história embaraçosa em 25 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 25.0),
        PhraseData(text: "[Name], nomeia 4 posições sexuais em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 3 elogios picantes em 20 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], imita um gemido em 10 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz 10 flexões em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 5 cidades portuguesas em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], bebe um shot em 5 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 5.0),
        PhraseData(text: "[Name], imita o sotaque alentejano em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 4 cantores portugueses em 10 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz uma pose sexy em 20 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], conta uma piada em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 3 sobremesas portuguesas em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz 5 saltos em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita um cão em 10 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], diz 5 palavras começadas por 'P' em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma careta em 10 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], bebe água em 8 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 8.0),
        PhraseData(text: "[Name], nomeia 4 rios portugueses em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita o sotaque minhoto em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 3 abdominais em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 5 animais em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz uma dança pimba em 25 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 25.0),
        PhraseData(text: "[Name], nomeia 3 festas populares em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita o Tony Carreira em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 5 passos de dança em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 4 bebidas alcoólicas em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], bebe um gole em 5 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 5.0),
        PhraseData(text: "[Name], imita um gato em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 5 jogadores de futebol em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz uma pose de yoga em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 3 provérbios portugueses em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 4 saltos estrela em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], imita o sotaque algarvio em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 5 monumentos portugueses em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 5 polichinelos em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 4 filmes portugueses em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], bebe um copo cheio em 10 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita um político em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 3 ilhas portuguesas em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz uma dança louca em 25 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 25.0),
        PhraseData(text: "[Name], diz 5 cores em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita um porco em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 3 poses sexy em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 4 clubes de futebol em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 5 saltos em 10 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], diz 3 nomes de santos em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita o sotaque lisboeta em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 5 frutas em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança lenta em 20 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], diz 4 marcas de vinho em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], bebe dois goles em 8 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 8.0),
        PhraseData(text: "[Name], imita um bebé em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 3 instrumentos musicais em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz 5 movimentos de ginástica em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], diz 5 palavras em inglês em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita o sotaque madeirense em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 4 pratos de peixe em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança de rua em 25 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 25.0),
        PhraseData(text: "[Name], diz 3 palavras picantes em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita um galo em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 5 flexões de braço em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 5 flores em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], bebe um shot de água em 5 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 5.0),
        PhraseData(text: "[Name], imita o sotaque açoriano em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 3 poses de modelo em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 4 nomes de actores portugueses em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança rápida em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 5 países em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita um pássaro em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 5 movimentos de braços em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 3 nomes de rios em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], imita o sotaque transmontano em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], nomeia 4 doces portugueses em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança tradicional em 25 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 25.0),
        PhraseData(text: "[Name], diz 5 palavras em espanhol em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita um cavalo em 15 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz 3 saltos altos em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], nomeia 5 carros em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança engraçada em 20 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], diz 4 palavras em francês em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita o sotaque portuense em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 5 passos para trás em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 3 marcas de roupa em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz uma pose de luta em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], diz 5 nomes de árvores em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita um peixe em 10 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz 3 movimentos de cabeça em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], nomeia 4 bandas portuguesas em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], faz uma dança de verão em 20 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], diz 5 palavras em italiano em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], imita o sotaque ribatejano em 20 segundos. Se ninguém rir, apanha 2 penalidades.", category: .timedChallenge, duration: 20.0),
        PhraseData(text: "[Name], faz 5 passos para a frente em 15 segundos ou apanha 3 penalidades.", category: .timedChallenge, duration: 15.0),
        PhraseData(text: "[Name], nomeia 3 tipos de peixe em 10 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 10.0),
        PhraseData(text: "[Name], faz uma pose de rei/rainha em 15 segundos ou apanha 2 penalidades.", category: .timedChallenge, duration: 15.0),
    ]
    
    private var currentPhraseIndex: Int = -1
    private var usedPhraseIndices: Set<Int> = []
    
    func addPlayer(_ name: String) -> Bool {
        guard players.count < maxPlayers, !name.isEmpty, !players.contains(name) else {
            return false
        }
        players.append(name)
        return true
    }
    
    func removePlayer(at index: Int) -> Bool {
        guard index >= 0, index < players.count else {
            return false
        }
        players.remove(at: index)
        return true
    }
    
    func canStartGame() -> Bool {
        return players.count >= 2
    }
    
    // Update getNextPhrase to return (String, PhraseCategory, Double?)
    func getNextPhrase() -> (text: String, category: PhraseCategory, duration: Double?)? {
        guard !phrases.isEmpty else { return nil } // Handle empty phrases array

        if usedPhraseIndices.count >= phrases.count {
            usedPhraseIndices.removeAll()
        }
        
        var nextIndex: Int
        repeat {
            nextIndex = Int.random(in: 0..<phrases.count)
        } while usedPhraseIndices.contains(nextIndex)
        
        currentPhraseIndex = nextIndex
        usedPhraseIndices.insert(nextIndex)
        
        let selectedPhraseData = phrases[nextIndex]
        let processedText = replacePlaceholders(in: selectedPhraseData.text)
        
        return (processedText, selectedPhraseData.category, selectedPhraseData.duration)
    }
    
    private func replacePlaceholders(in phrase: String) -> String {
        var result = phrase
        while result.contains("[Name]") {
            if let randomIndex = players.indices.randomElement() {
                result = result.replacingOccurrences(
                    of: "[Name]",
                    with: players[randomIndex],
                    options: .literal,
                    range: result.range(of: "[Name]")
                )
            } else {
                break
            }
        }
        return result
    }
    
    func resetGame() {
        currentPhraseIndex = -1
        usedPhraseIndices.removeAll()
        players.removeAll()
    }
    
    func resetCurrentGame() {
        currentPhraseIndex = -1
        usedPhraseIndices.removeAll()
    }
}
